<?php
$title = ($this->translate('Photos Bénéficiaires / En attente'));
$this->headTitle($title);
?>
<script type="text/javascript">
    $(document).ready(function () {

    $('.btnBackToOrigImage').on("click", function () {
    var photoId = $(this).attr("data-photoId");
            $.ajax({
            type: 'GET',
                    url: '<?php echo $this->url('Photosmgmt', array('action' => 'backtooriginal')); ?>/' + photoId,
                    dataType: 'json',
                    success: function (data) {

                    //window.location.reload(true);
                    if (data['state'] == "ok") {

                    loadImages();
                            $('#modalPhoto' + photoId).modal('hide');
                            window.location.href = '<?php echo $this->url('Photosmgmt', array('action' => 'index')); ?>';
                    }
                    else {
                    $('#modalPhoto' + photoId).modal('hide');
                            dialogInfo(false, "Une erreur est survenue<br>" + data['error'], "Fermer");
                    }

                    },
                    error: function (error) {
                    $('#modalPhoto' + photoId).modal('hide');
                            dialogInfo(false, "Une erreur est survenue", "Fermer");
                    }

            });
            });
            $('.submitbutton').on("click", function () {
                loadImages();
                $(this).parent().parent().submit();
            });
            loadImages();
            $(".imgAsync").on("click", function () {
                var image = $(this).attr("data-imagesrc");
                var idImage = "idImage";
                bootbox.dialog('<img class="img-responsive" src="' + image + '" id="'+idImage+'"/>', [{
                "label": "Fermer",
                        "class": "btn-success",
                        "keyboard": true,
                        "callback": function () {


                        }
                }]);

                $('.bootbox').prepend('<div class="modal-header">'+
                '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>'+
                '<h4 class = "modal-title">Photo</h4>'+
                '</div>');
        
                $('.bootbox').css('background-color', 'white');
                $('.bootbox').css('width', '520px');
                $('.bootbox').css('margin', '0 auto');
                $('.bootbox').css('margin-top', '20px');
                $('.bootbox').css('border', '1px solid #e5e5e5');
                $('.bootbox').css('height', '0px');
                
                setTimeout(function(){
                    var img = document.getElementById(idImage); 
                    var height = img.naturalHeight;
                    if(height >500){
                        $('.bootbox').css('margin-top', '10px');
                        $('.bootbox').css('height', "660px");
                    }
                    else{
                        $('.bootbox').css('margin-top', '80px');
                        $('.bootbox').css('height', (height+170)+"px");
                    }
                    
                }, 650);
                
            });
        });
            function loadImages() {
            $('.imgAsync').loadImages({
            imgLoadedClb: function () {
            },
                    allLoadedClb: function () {
                    },
                    imgErrorClb: function () {
                    },
                    noImgClb: function () {
                    },
                    dataAttr: 'src'
            });
            }


    function dialogInfo(isOk, message, btnLabel) {

    var classBtn = "btn-danger";
            if (isOk) {
    classBtn = "btn-success";
    }
    bootbox.dialog(message, [{
    "label": btnLabel,
            "class": classBtn,
            "callback": function () {

            window.location.href = '<?php echo $this->url('Photosmgmt', array('action' => 'index')); ?>';
            }
    }]);
            $('.bootbox').css('background-color', 'white');
            $('.bootbox').css('width', '300px');
            $('.bootbox').css('min-height', '120px');
            $('.bootbox').css('margin', '0 auto');
            $('.bootbox').css('margin-top', '250px');
    }
</script>    
<!-- Photos Beneficiaire -->
<div id="page-wrapper">
    <div class="row"><div class="col-lg-12"><h1 class="page-header"><?php echo $title; ?></h1></div></div>

    <table class="table table-striped table-hover">
        <thead><tr><th width="1">Photo</th><th width="1">Date</th><th>Auteur</th><th>Commentaire</th><th>Action</th></tr></thead>
        <tbody>
<?php
foreach ($photos as $ph) :
//die('<pre>'.print_r($ph,true).'</pre>');
    ?>
                <tr>
                    <td><img width="170" height="168" class="img<?php echo $ph['photoId']; ?> imgAsync" data-src="<?php echo $this->basePath(); ?>/filesbank/thumbnails/<?php echo $ph['Vignette'] . '?' . time(); ?>" data-imagesrc="<?php echo $this->basePath(); ?>/filesbank/<?php echo $ph['Image'] . '?' . time(); ?>"></td>
                    <td><?php echo $ph['Date'] ?></td>
                    <td><?php echo htmlentities($ph['Auteur'], ENT_NOQUOTES, "ISO8859-15"); ?></td>
                    <td><?php echo htmlentities($ph['Commenter'], ENT_NOQUOTES, "ISO8859-15"); ?></td>
                    <td>
                        <a href="" data-target="#modalPhoto<?php echo $ph['photoId']; ?>" data-toggle="modal" class="actionPhotosIcon btn btn-warning btn-circle"><i class="fa fa-wrench">&nbsp;</i>&nbsp;</a>
                        <a href="" data-action="<?php print($this->basePath() . '/photosmgmt/setvalider/' . $ph['photoId']); ?>" data-toggle="confirmation" class="actionPhotosIcon btn btn-success btn-circle"><i class="fa fa-check">&nbsp;</i>&nbsp;</a>
                        <a href="" data-action="<?php print($this->basePath() . '/photosmgmt/setsupprimer/' . $ph['photoId']); ?>" data-toggle="confirmation" class="actionPhotosIcon btn btn-danger btn-circle"><i class="fa fa-times">&nbsp;</i>&nbsp;</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

<?php
if (empty($photos)) {
    print('<p style="color:red">Toutes les photos sont validées</p>');
}
?>


<?php
foreach ($photos as $ph) :
//die('<pre>'.print_r($ph,true).'</pre>');
    ?>
        <div class="modal fade" id="modalPhoto<?php echo $ph['photoId']; ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog"><div class="modal-content"><div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Photo</h4>
                    </div>
                    <div class="modal-body row">
                        <div class="col-lg-5">
                            <img width="170" height="168" class="img<?php echo $ph['photoId']; ?> imgAsync" data-src="<?php echo $this->basePath(); ?>/filesbank/thumbnails/<?php echo $ph['Vignette'] . '?' . time(); ?>"  data-imagesrc="<?php echo $this->basePath(); ?>/filesbank/<?php echo $ph['Image'] . '?' . time(); ?>"><br>
                            <a data-img="img<?php echo $ph['photoId']; ?>" href="<?php echo $this->basePath() . '/photosmgmt/rotateright/' . $ph['photoId']; ?>" class="ajaxRotate btn btn-warning btn-circle"><i class="fa fa-rotate-right"></i></a>
                            <a data-img="img<?php echo $ph['photoId']; ?>" href="<?php echo $this->basePath() . '/photosmgmt/rotateleft/' . $ph['photoId']; ?>" class="ajaxRotate btn btn-warning btn-circle"><i class="fa fa-rotate-left"></i></a>
                        </div>
                        <div class="col-lg-7">

                            <form method="post" action="<?php print($this->basePath() . '/photosmgmt/update/' . $ph['photoId']); ?>" id="validatePhotoForm">
                                <p><strong>Auteur :</strong> <?php echo $ph['Auteur']; ?></p>
                                <p><strong>NIA :</strong> <?php echo $ph['NIA']; ?></p>
                                <p><strong>Email :</strong> <?php echo $ph['Email']; ?></p>
                                <p><strong>Date :</strong> <?php echo $ph['Date']; ?></p>
                                <p><strong>GPS :</strong> <?php echo $ph['lat']; ?> / <?php echo $ph['lng']; ?></p>
                                <p><strong>Commenter :</strong><br>
                                    <textarea name="commenter" rows="8" class="form-control"><?php echo $ph['Commenter']; ?></textarea>
                                </p>

                                <p style="float:right;width:24%;"> 
                                    <input type="hidden" name="status" value="<?php echo $ph['status']; ?>">
                                    <input type="button" name="submitbutton" value="Valider"style="font-size: 14px;width:100%;height:62px;"  class="submitbutton btn btn-lg btn-success">
                                </p>

                                <button data-photoId="<?php echo $ph['photoId']; ?>" style="float:right; margin-right:3%;font-size: 14px;width:41%;height:62px;" type="button" class="btnBackToOrigImage btn btn-lg btn-default">Retour &agrave;<br>l'image d'origine</button>
                                <button style="float:right; margin-right:3%;font-size: 14px;width:28%;height:62px;" type="button" class="btn btn-lg btn-default" data-dismiss="modal">Fermer<br>la fen&ecirc;tre</button>
                                <p class="clearboth"></p>
                            </form>
                        </div>
                        <p class="clearboth"></p>
                    </div>
                </div>
            </div>
        </div>
<?php endforeach; ?>

</div>
