<?php
$title = $this->translate('Push - Nouveau');
$this->headTitle($title);
?>
<script type="text/javascript">
    $(document).ready(function () {
       
        $('#btnpushnotifsubmit').on('click', function () {
            if(document.pushnotifform.cible.value == "Prod"){
                dialogInfo(true, "&Ecirc;tes-vous s&ucirc;r d'envoyer la notification en Production ?", "Confirmer");
            }
            else{
                dialogInfo(true, "&Ecirc;tes-vous s&ucirc;r d'envoyer la notification de test ?", "Confirmer");
            }
        });
        
        
        function dialogInfo(isOk, message, btnLabel) {

        var classBtn = "btn-danger";

        if (isOk) {
            classBtn = "btn-success";
        }
        bootbox.dialog(message, [
            {
                "label": "Annuler",
                "class": "btn btn-default",
                "callback": function () {
                    window.location.href = '<?php echo $this->url('pushnotif', array('action' => 'add')); ?>';
                }       
            },
            {
                "label": btnLabel,
                "class": classBtn,
                "callback": function () {
                    document.forms[0].submit();
                    
                }
            }
            ]);
            
            $('.bootbox').css('background-color', 'white');
            $('.bootbox').css('width', '300px');
            $('.bootbox').css('height', '120px');
            $('.bootbox').css('margin', '0 auto');
            $('.bootbox').css('margin-top', '250px');
    }
    });



</script>    
<div id="page-wrapper">
    <div class="row"><div class="col-lg-12"><h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1></div></div>

    <form id="pushnotifform" method="post" name="pushnotifform" action="<?php echo $this->url('pushnotif', array('action' => 'new')); ?>">

        <div class="form-group col-md-6">
            <label>Cible</label>
            <select class="form-control" name="cible">
                <option value="Dev">SmartPhones de Test</option>
                <option value="Prod">SmartPhones Bénéficiaires</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label>Type de push</label>
            <select class="form-control" name="pushType">
                <option value="simple">Push Simple</option>
                <option value="deep">Push Profond</option>
            </select>
        </div>

        <div id="pushProfond">
            <div class="form-group col-md-12">
                <label>Destination</label>
                <select class="form-control" name="pushDestination">
                    <option value="">Sélectionner</option>
                    <option value="1">Vacance : Résultat de recherche</option>
                    <option value="2">Vacance : Fiche séjour</option>
                    <option value="3">Journal : Actualités rubrique</option>
                    <option value="4">Journal : Article</option>
                </select>
            </div>

            <!-- Résultat de recherche -->
            <div class="PushDestiRecherche" id="destination1">
                <div class="form-group col-md-6">
                    <label class="col-md-3">Région</label>
                    <ul class="noPoint col-md-9">
                        <li><input type="checkbox" name="d1Region[]" value="7"> Bretagne - Vendée</li>
                        <li><input type="checkbox" name="d1Region[]" value="8"> Centre</li>
                        <li><input type="checkbox" name="d1Region[]" value="9"> Corse</li>
                        <li><input type="checkbox" name="d1Region[]" value="2"> Est</li>
                        <li><input type="checkbox" name="d1Region[]" value="13"> Etranger</li>
                        <li><input type="checkbox" name="d1Region[]" value="5"> Languedoc - Roussillon - Midi-Pyrénées</li>
                        <li><input type="checkbox" name="d1Region[]" value="1"> Nord</li>
                        <li><input type="checkbox" name="d1Region[]" value="11"> Normandie - Pays de Loire</li>
                        <li><input type="checkbox" name="d1Region[]" value="10"> Outre-mer</li>
                        <li><input type="checkbox" name="d1Region[]" value="12"> Paris - Ile de France</li>
                        <li><input type="checkbox" name="d1Region[]" value="4"> Provence - Alpes - Côtes d´Azur</li>
                        <li><input type="checkbox" name="d1Region[]" value="3"> Rhône - Alpes</li>
                        <li><input type="checkbox" name="d1Region[]" value="6"> Sud - Ouest</li>
                    </ul>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-md-5">Environnement</label>
                    <ul class="noPoint col-md-7">
                        <li><input type="checkbox" name="d1Environ[]" value="C"> Campagne</li>
                        <li><input type="checkbox" name="d1Environ[]" value="M"> Mer</li>
                        <li><input type="checkbox" name="d1Environ[]" value="MO"> Montagne</li>
                        <li><input type="checkbox" name="d1Environ[]" value="V"> Ville</li>
                    </ul>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-md-5">Type d´hébergement</label>
                    <ul class="noPoint col-md-7">
                        <li><input type="checkbox" name="d1Accom[]" value="CL"> Campeurs</li>
                        <li><input type="checkbox" name="d1Accom[]" value="G"> GÎtes</li>
                        <li><input type="checkbox" name="d1Accom[]" value="GTS"> GÎtes sans restauration</li>
                        <li><input type="checkbox" name="d1Accom[]" value="MF"> Maison familiale</li>
                        <li><input type="checkbox" name="d1Accom[]" value="TC"> Terrain de camping</li>
                        <li><input type="checkbox" name="d1Accom[]" value="VSL"> Village de structure légère</li>
                        <li><input type="checkbox" name="d1Accom[]" value="VT"> Village de toile</li>
                    </ul>
                </div>
                <div class="col-md-12"></div>
                <div class="form-group col-md-6">
                    <label class="col-md-12">Taille du logement (places)</label>
                    <select class="noPoint form-control" name="d1Taille">
                        <option value="0">Tous</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label class="col-md-12">Accueil Handicapé</label>
                    <select class="noPoint form-control" name="d1Accueil[]">
                        <option value=""></option>
                        <option value="HR">Oui</option>
                        <option value="">Non</option>
                    </select>
                </div>
                <div class="form-group col-md-12">
                    <label class="col-md-4">Equipement</label>
                    <ul class="noPoint col-md-4">
                        <li><input type="checkbox" name="d1Equip[]" value="B"> Espace boisson</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E1"> Minigolf</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E10"> Piscine</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E11"> Accueil handicapé : joelette</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E12"> Accueil handicapé : tiralo</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E13"> Accueil handicapé : Fauteuil ski</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E2"> Court de tennis</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E3"> Court de tennis éclairé</li>
                    </ul>
                    <ul class="noPoint col-md-4">
                        <li><input type="checkbox" name="d1Equip[]" value="E4"> Tennis de table</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E5"> Tir à l´arc</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E6"> Aire de jeux enfants</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E7"> Bibliothèque </li>
                        <li><input type="checkbox" name="d1Equip[]" value="E8"> Salon télévision</li>
                        <li><input type="checkbox" name="d1Equip[]" value="E9"> Activités nautiques</li>
                        <li><input type="checkbox" name="d1Accueil[]" value="CE"> Clubs Enfants</li>
                        <li><input type="checkbox" name="d1Accueil[]" value="CA"> Animaux acceptés</li>
                    </ul>
                </div>
            </div><!-- FIN Résultat de recherche -->


            <!-- Fiche séjour -->
            <div class="PushDestiRecherche" id="destination2">
                <div class="form-group col-md-4">
                    <label>Année</label>
                    <input type="text" class="form-control" name="d2Annee" value="<?php echo date('Y') ?>" pattern="[0-9]{4}">
                </div>
                <div class="form-group col-md-4">
                    <label>Saison</label>
                    <select class="form-control" name="d2Saison">
                        <option value="P">Printemps</option>
                        <option value="E">Eté</option>
                        <option value="A">Automne</option>
                        <option value="H">Hiver</option>
                    </select>
                </div>
                <div class="form-group col-md-4">
                    <label>Code Séjour</label>
                    <input type="text" class="form-control" name="d2Identifiant" value="" pattern="[a-zA-Z0-9]{3}">
                </div>
            </div><!-- FIN Fiche séjour -->

            <!-- Fiche Actualités du magazine -->
            <div class="PushDestiRecherche" id="destination3">
                <div class="form-group col-md-12">
                    <label>Theme</label>
                    <select class="form-control" name="d3Theme">
                        <option value="alaune">A la une</option>
                        <option value="vacances">Vacances</option>
                        <option value="colos">Colos</option>
                        <option value="sports">Sports</option>
                        <option value="culture">Culture</option>
                        <option value="sante-action-sociale">Santé Social</option>
                        <option value="actualite-sociale">Actu sociale</option>
                        <option value="solidarite">Solidarité</option>
                        <option value="international">International</option>
                        <option value="developpement-durable">Développement Durable</option>
                        <!--<option value="11">Dossier</option>-->
                    </select>
                </div>
            </div><!-- FIN Actualités du magazine -->

            <!-- Fiche Fiche Article -->
            <div class="PushDestiRecherche" id="destination4">
                <div class="form-group col-md-6">
                    <label>Theme</label>
                    <select class="form-control" name="d4Theme">
                        <option value="alaune">A la une</option>
                        <option value="vacances">Vacances</option>
                        <option value="colos">Colos</option>
                        <option value="sports">Sports</option>
                        <option value="culture">Culture</option>
                        <option value="sante-action-sociale">Santé Social</option>
                        <option value="actualite-sociale">Actu sociale</option>
                        <option value="solidarite">Solidarité</option>
                        <option value="international">International</option>
                        <option value="developpement-durable">Développement Durable</option>
                        <!--<option value="11">Dossier</option>-->
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label>Position de l'article dans le theme</label>
                    <input type="text" class="form-control" name="d4Position" value="1" pattern="[0-9]+">
                </div>
            </div><!-- FIN Actualités du magazine -->
        </div>


        <div class="form-group col-md-12">
            <label>Message du push</label>
            <textarea class="form-control" name="message"></textarea>
        </div>

        <div class="form-group col-md-12">
            <p class="submit clearboth">
                <input type="button" name="btnSubmit" id="btnpushnotifsubmit" value="Envoyer" class="btn btn-success">
            </p>
        </div>
    </form>
</div>
