<?php
// module/Rubrique/view/rubrique/rubrique/index.phtml:
$title = $this->translate('Push - Historique');
$this->headTitle($title);
//echo $session->test;
?>

<div id="page-wrapper">
	<div class="row"><div class="col-lg-12"><h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1></div></div>
	<table class="table table-striped table-hover">
	<thead><tr><th>Date</th><th>Message</th><th>Type</th><th>Status</th><th>Enviro</th><th>Action</th><!--<th>Type</th>--></tr></thead>
	<tbody>
<?php
foreach($pushs as $u) :
//die('<pre>'.print_r($ph,true).'</pre>');
?>
<tr>
	<td><?php print($u['pushDate']); ?></td>
	<td><?php print($u['pushMsg']); ?></td>
	<td><?php echo ($u['pushType'] == 1 ? 'Simple' : 'Profond'); ?></td>
	<td><?php print($u['pushStatus']); ?></td>
	<td><?php print($u['environement']); ?></td>
	<td class="centr">
		<a href="" data-target="#modalPush<?php echo $this->escapeHtml($u['pushId']); ?>" data-toggle="modal" class="btn btn-warning btn-circle actionLoginIcon"><i class="fa fa-wrench"></i></a>
		<!--<a href="" data-action="<?php /*echo $this->url('loginmgmt', array('action' => 'delete', 'id' => $u['userId']));*/ ?>" data-toggle="confirmation" class="btn btn-danger btn-circle"><i class="fa fa-times"></i></a>-->
	</td>
	</tr>
<?php endforeach; ?>
	</tbody>
	</table>
</div>

<?php
foreach($pushs as $u) :
//die('<pre>'.print_r($ph,true).'</pre>');
?>
<div class="modal fade" id="modalPush<?php echo $this->escapeHtml($u['pushId']); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog"><div class="modal-content"><div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
<h4 class="modal-title">Détail Push du <?php echo $this->escapeHtml($u['pushDate']); ?></h4>
</div>
<div class="modal-body row">
	<div class="col-lg-12">
		<p class="col-lg-3">Type :</p>
			<p class="col-lg-9"><?php echo ($u['pushType'] == 1 ? 'Push simple' : 'Push profond'); ?></p>
		<p class="col-lg-3">Message :</p>
			<p class="col-lg-9"><?php echo $this->escapeHtml($u['pushMsg']); ?></p>

		<!-- Push Profond uniquement -->
		<div style="<?php echo ($u['pushType'] == 2 ? '' : 'display:none') ?>">
			<p class="col-lg-3">Destination :</p>
				<p class="col-lg-9"><?php
				if($u['pushDestination'] == 1) echo 'R&#233;sultat de recherche';
				elseif($u['pushDestination'] == 2) echo 'Fiche s&#233;jour';
				elseif($u['pushDestination'] == 3) echo 'Actualit&#233;s';
				elseif($u['pushDestination'] == 4) echo 'Fiche Article';
				?></p>
			<p class="col-lg-3">Destination (id) :</p>
				<p class="col-lg-9"><?php echo $u['pushDestinationId']; ?></p>
		</div>
		<p>Détail de l'envoi</p>
			<p class="col-lg-3">Push Android :</p>
			<p class="col-lg-9"><?php 
                            $pushAndroid = wordwrap($u['pushAndroid'], 45, "<br>\n",true); 
                            echo $pushAndroid; ?>&nbsp;</p>
			<p class="col-lg-3">Push iOS :</p>
			<p class="col-lg-9"><?php 
                            $pushIOS = wordwrap($u['pushIOS'], 45, "<br>\n",true); 
                            echo $pushIOS;
                        ?>&nbsp;</p>
	</div>
	<p class="clearboth"></p>
</div>
</div>
</div>
</div>
<?php
endforeach;
?>