<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="robots" content="noindex">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <!-- Favicon -->
        <link rel="shortcut icon" href="../../favicon.ico">

        <?php echo $this->headTitle(' ' . $this->translate('At night and in transportation'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Les styles -->
        <!-- Google Fonts -->
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans%3A400%2C300%2C500%2C600%2C700">

        <!-- CSS Global Compulsory -->
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/javascript/bootstrap/bootstrap.css';?>">

        <!-- CSS Implementing Plugins -->
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/css/icon-awesome/css/font-awesome.min.css';?>">
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/css/icon-line/css/simple-line-icons.css';?>">
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/css/icon-line-pro/style.css';?>">
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/css/icon-hs/style.css';?>">
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/css/animate.css';?>">
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/css/hs-megamenu/src/hs.megamenu.css';?>">
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/css/hamburgers/hamburgers.css';?>">

        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css';?>">
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/css/settings.css';?>">
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/css/layers.css';?>">
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/css/navigation.css';?>">

        <!-- CSS Unify -->
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/anitcms/css/unify.css';?>">

        <!-- CSS Customization -->
        <link rel="stylesheet" href=""<?php echo $this->basePath() . '/anitcms/css/custom.css';?>">
        <?php
        //Problem with chrome and favicon that disturb session management : https://pritisolanki.wordpress.com/tag/zend-framework-session-problem-in-chrome/
        /*$linkico = "http://localhost:10088/mobiletools/public/atnightintrain.ico";
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $linkico))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')*/
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/anitcms/javascript/jquery/jquery-3.2.1.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/anitcms/javascript/jquery-migrate/jquery-migrate.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/anitcms/javascript/tether.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/anitcms/javascript/bootstrap/bootstrap.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/anitcms/javascript/appear.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/anitcms/javascript/hs-megamenu/src/hs.megamenu.js'; ?>"></script>
        <!-- JS Revolution Slider -->
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/jquery.themepunch.tools.min.js';?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/jquery.themepunch.revolution.min.js';?>"></script>

        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution-addons/slicey/js/revolution.addon.slicey.min.js';?>"></script>

        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/extensions/revolution.extension.actions.min.js';?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/extensions/revolution.extension.carousel.min.js';?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/extensions/revolution.extension.kenburn.min.js';?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/extensions/revolution.extension.layeranimation.min.js';?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/extensions/revolution.extension.migration.min.js';?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/extensions/revolution.extension.navigation.min.js';?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/extensions/revolution.extension.parallax.min.js';?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/extensions/revolution.extension.slideanims.min.js';?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/revolution-slider/revolution/js/extensions/revolution.extension.video.min.js';?>"></script>

        <!-- JS Unify -->
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/js/hs.core.js'; ?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/js/components/hs.header.js'; ?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/js/helpers/hs.hamburgers.js'; ?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/js/components/hs.tabs.js'; ?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/js/components/hs.onscroll-animation.js'; ?>"></script>
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/js/components/hs.go-to.js'; ?>"></script>

        <!-- JS Customization -->
        <script src="<?php echo $this->basePath() . '/anitcms/javascript/js/custom.js'; ?>"></script>

        <!-- JS Plugins Init. -->
        <script>
            // initialization of slider revolution
            var tpj = jQuery,
                revapi26;

            tpj(document).ready(function () {
                if (tpj("#rev_slider_26_1").revolution == undefined) {
                    revslider_showDoubleJqueryError("#rev_slider_26_1");
                } else {
                    revapi26 = tpj("#rev_slider_26_1").show().revolution({
                        sliderType: "standard",
                        jsFileLocation: "revolution/js/",
                        sliderLayout: "fullscreen",
                        dottedOverlay: "none",
                        delay: 9000,
                        navigation: {
                            keyboardNavigation: "off",
                            keyboard_direction: "horizontal",
                            mouseScrollNavigation: "off",
                            mouseScrollReverse: "default",
                            onHoverStop: "off",
                            touch: {
                                touchenabled: "on",
                                touchOnDesktop: "off",
                                swipe_threshold: 75,
                                swipe_min_touches: 1,
                                swipe_direction: "horizontal",
                                drag_block_vertical: false
                            },
                            arrows: {
                                style: "uranus",
                                enable: true,
                                hide_onmobile: true,
                                hide_under: 778,
                                hide_onleave: false,
                                tmp: '',
                                left: {
                                    h_align: "left",
                                    v_align: "center",
                                    h_offset: 15,
                                    v_offset: 0
                                },
                                right: {
                                    h_align: "right",
                                    v_align: "center",
                                    h_offset: 15,
                                    v_offset: 0
                                }
                            },
                            bullets: {
                                enable: true,
                                hide_onmobile: false,
                                style: "bullet-bar",
                                hide_onleave: false,
                                direction: "horizontal",
                                h_align: "center",
                                v_align: "bottom",
                                h_offset: 0,
                                v_offset: 30,
                                space: 5,
                                tmp: ''
                            }
                        },
                        responsiveLevels: [1240, 1024, 778, 480],
                        visibilityLevels: [1240, 1024, 778, 480],
                        gridwidth: [1240, 1024, 778, 480],
                        gridheight: [868, 768, 960, 720],
                        lazyType: "none",
                        parallax: {
                            type: "scroll",
                            origo: "slidercenter",
                            speed: 2000,
                            levels: [5, 10, 15, 20, 25, 30, 35, 40, 45, 46, 47, 48, 49, 50, 51, 55]
                        },
                        shadow: 0,
                        spinner: "off",
                        stopLoop: "off",
                        stopAfterLoops: -1,
                        stopAtSlide: -1,
                        shuffle: "off",
                        autoHeight: "off",
                        fullScreenAutoWidth: "off",
                        fullScreenAlignForce: "off",
                        fullScreenOffsetContainer: "",
                        fullScreenOffset: "60px",
                        hideThumbsOnMobile: "off",
                        hideSliderAtLimit: 0,
                        hideCaptionAtLimit: 0,
                        hideAllCaptionAtLilmit: 0,
                        debugMode: false,
                        fallbacks: {
                            simplifyAll: "off",
                            nextSlideOnWindowFocus: "off",
                            disableFocusListener: false
                        }
                    });
                }
            });

            $(document).on('ready', function () {
                // initialization of tabs
                $.HSCore.components.HSTabs.init('[role="tablist"]');

                // initialization of scroll animation
                $.HSCore.components.HSOnScrollAnimation.init('[data-animation]');

                // initialization of go to
                $.HSCore.components.HSGoTo.init('.js-go-to');
            });

            $(window).on('load', function () {
                // initialization of header
                $.HSCore.components.HSHeader.init($('#js-header'));
                $.HSCore.helpers.HSHamburgers.init('.hamburger');

                // initialization of HSMegaMenu component
                $('.js-mega-menu').HSMegaMenu({
                    event: 'hover',
                    pageContainer: $('.container'),
                    breakpoint: 991
                });
            });

            $(window).on('resize', function () {
                setTimeout(function () {
                    $.HSCore.components.HSTabs.init('[role="tablist"]');
                }, 200);
            });
        </script>


        <link href="<?php echo $this->basePath() . "/js/datatable/media/css/jquery.dataTables.min.css"; ?>" rel='stylesheet'/>
    </head>
    <body>
        <main>
            <?php
            echo $this->content;
            ?>

        </main> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
