<div id="page-wrapper" style="min-height: 248px;">
<?php
// module/Album/view/sousrubrique/sousrubrique/delete.phtml:
$title = $this->translate('Supprimer un fichier de configuration');
$this->headTitle($title);
?>
<?php //print_r($sousrubrique); ?>
<h1><?php echo $title; ?></h1>
<p><?php echo $this->translate('Etes-vous sûr de vouloir supprimer ce ficher de configuration'); ?>&nbsp;'<?php echo $fichiers->getLibelle(); ?>'?
</p>
<?php
	$url = $this->url('Confmgmt', array(
		'action' => 'delete',
		'id' => $this->id,
	));
?>

<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo (int)$fichiers->getId(); ?>" />
		<input type="submit" name="del" value="<?php echo $this->translate('Oui') ?>" />
		<input type="submit" name="del" value="<?php echo $this->translate('Non') ?>" />
	</div>
</form>
</div>