<?php
$title = $this->translate('Modifier la description associées au fichier de configuration');
$this->headTitle($title);
?>
<style>
div input[type="submit"]{
	width:80px;
	height:40px;
}

</style>

<div id="page-wrapper" style="min-height: 248px;">
<h1><?php echo $title; ?></h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('Confmgmt', array('action' => 'edit')));
	if($error!="no error"){
		echo '<div style="color:red;">'.$error.'</div>';
	}
	
	$form->prepare();
	
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo '<div>'.$this->translate('Courte description').'</div>';
	//Prod ISO 8859 1
        echo $this->formRow($form->get('libelle')).'<br><br>';
        echo '<div style="display:none;">'.$this->translate('Meta data').'</div>';
	echo '<div style="display:none;">'.$this->formRow($form->get('metadata')).'</div>';
	echo '<div>&nbsp;</div>';
	echo '<div>'.$this->formSubmit($form->get('submit')).'</div>';
	
	echo $this->form()->closeTag();
  ?>
</div>