<?php
$title = $this->translate('Photos Validées');
$this->headTitle($title);
?>
<script type="text/javascript">
    $(document).ready(function () {

        $('.btnBackToOrigImage').on("click", function () {
            var id = $(this).attr("data-id");
            $.ajax({
                type: 'GET',
                url: '<?php echo $this->url('Uploadmgmt', array('action' => 'backtooriginal')); ?>/' + id,
                dataType: 'json',
                success: function (data) {

                    //window.location.reload(true);
                    if (data['state'] == "ok") {

                        loadImages();
                        $('#modalPhoto' + id).modal('hide');

                        window.location.href = '<?php echo $this->url('Uploadmgmt', array('action' => 'validatedfiles')); ?>';
                    }
                    else {
                        $('#modalPhoto' + id).modal('hide');
                        dialogInfo(false, "<?php echo $this->translate('Une erreur est survenue<br>'); ?>" + data['error'], "Fermer");
                    }

                },
                error: function (error) {
                    $('#modalPhoto' + id).modal('hide');
                    dialogInfo(false, "<?php echo $this->translate("Une erreur est survenue"); ?>", "<?php echo $this->translate("Fermer"); ?>");
                }

            });
        });

        $('.submitbutton').on("click", function () {
            loadImages();
            $(this).parent().parent().submit();
        });

        loadImages();

        $(".photoFull").on("click", function () {
            var image = $(this).attr("data-imagesrc");
            var idImage = "idImage";
            bootbox.dialog('<img class="img-responsive" src="' + image + '" id="' + idImage + '"/>', [{
                "label": "Fermer",
                "class": "btn-success",
                "keyboard": true,
                "callback": function () {


                }
            }]);

            $('.bootbox').prepend('<div class="modal-header">' +
                '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                '<h4 class = "modal-title"><?php echo $this->translate('Fichiers'); ?></h4>' +
                '</div>');

            $('.bootbox').css('background-color', 'white');
            $('.bootbox').css('width', '520px');
            $('.bootbox').css('margin', '0 auto');
            $('.bootbox').css('margin-top', '20px');
            $('.bootbox').css('border', '1px solid #e5e5e5');
            $('.bootbox').css('height', '0px');

            setTimeout(function () {
                var img = document.getElementById(idImage);
                var height = img.naturalHeight;
                if (height > 500) {
                    $('.bootbox').css('margin-top', '10px');
                    $('.bootbox').css('height', "660px");
                }
                else {
                    $('.bootbox').css('margin-top', '80px');
                    $('.bootbox').css('height', (height + 170) + "px");
                }

            }, 650);

        });

    });

    function loadImages() {
        $('.imgAsync').loadImages({
            imgLoadedClb: function () {
            },
            allLoadedClb: function () {
            },
            imgErrorClb: function () {
            },
            noImgClb: function () {
            },
            dataAttr: 'src'
        });
    }


    function dialogInfo(isOk, message, btnLabel) {

        var classBtn = "btn-danger";

        if (isOk) {
            classBtn = "btn-success";
        }
        bootbox.dialog(message, [{
            "label": btnLabel,
            "class": classBtn,
            "callback": function () {

                window.location.href = '<?php echo $this->url('Uploadmgmt', array('action' => 'index')); ?>';
            }
        }]);


        $('.bootbox').css('background-color', 'white');
        $('.bootbox').css('width', '300px');
        $('.bootbox').css('min-height', '120px');
        $('.bootbox').css('margin', '0 auto');
        $('.bootbox').css('margin-top', '250px');

    }
</script>


<!-- Photos Beneficiaire -->
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12"><h1 class="page-header"><?php echo $title; ?></h1></div>
    </div>

    <?php
    foreach ($photos as $ph) :
//die('<pre>'.print_r($ph,true).'</pre>');
        ?>
        <div class="col-xs-3 col-lg-2 text-center" style="padding-top:15px;padding-bottom:15px">
            <a href="#" data-toggle="modal" data-target="#modalPhoto<?php echo $ph['id']; ?>">
                <img width="100" height="99" class="img<?php echo $ph['id']; ?> imgAsync"
                     data-src="<?php echo $this->basePath() . $ph['path'] . $ph['thumbnailpath'] . $ph['thumbnail'] . '?' . time(); ?>">
            </a>
        </div>
    <?php endforeach; ?>

    <?php
    foreach ($photos as $ph) :
//die('<pre>'.print_r($ph,true).'</pre>');
        ?>
        <div class="modal fade" id="modalPhoto<?php echo $ph['id']; ?>" tabindex="-1" role="dialog"
             aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"><?php echo $this->translate('Fichiers'); ?></h4>
                    </div>
                    <div class="modal-body row">
                        <div class="col-lg-5">
                            <img width="170" height="168"
                                 class="img<?php echo $ph['id']; ?> imgAsync photoFull img-responsive"
                                 data-src="<?php echo $this->basePath(); ?>/filesbank/thumbnails/<?php echo $ph['Vignette'] . '?' . time(); ?>"
                                 data-imagesrc="<?php echo $this->basePath(); ?>/filesbank/<?php echo $ph['Image'] . '?' . time(); ?>"><br>
                            <a data-img="img<?php echo $ph['id']; ?>"
                               href="<?php echo $this->url('Uploadmgmt', array('action' => 'rotateright', 'id' => $ph['id'])); ?>"
                               class="ajaxRotate btn btn-warning btn-circle"><i class="fa fa-rotate-right"></i></a>
                            <a data-img="img<?php echo $ph['id']; ?>"
                               href="<?php echo $this->url('Uploadmgmt', array('action' => 'rotateleft', 'id' => $ph['id'])); ?> ?>"
                               class="ajaxRotate btn btn-warning btn-circle"><i class="fa fa-rotate-left"></i></a>
                        </div>
                        <div class="col-lg-7">

                            <form method="post"
                                  action="<?php print($this->url('Uploadmgmt', array('action' => 'update', 'id' => $ph['id']))); ?>">
                                <p><strong><?php echo $this->translate('Auteur'); ?>
                                        :</strong> <?php echo $ph['author']; ?></p>
                                <p><strong><?php echo $this->translate('Identifiant'); ?>
                                        :</strong> <?php echo $ph['userId']; ?></p>
                                <p><strong><?php echo $this->translate('email'); ?>
                                        :</strong> <?php echo $ph['email']; ?></p>
                                <p><strong><?php echo $this->translate('date'); ?>
                                        :</strong> <?php echo $ph['creationDate']; ?></p>
                                <p><strong><?php echo $this->translate('GPS'); ?>:</strong> <?php echo $ph['lat']; ?>
                                    / <?php echo $ph['lng']; ?></p>
                                <p><strong><?php echo $this->translate('Commenter'); ?>:</strong><br>
                                    <textarea name="commenter" rows="8"
                                              class="form-control"><?php echo $ph['comment']; ?></textarea>
                                </p>
                                <p style="float:right;width:24%;">
                                    <input type="hidden" name="status" value="<?php echo $ph['status']; ?>">
                                    <input type="button" name="submitbutton"
                                           value="<?php echo $this->translate('Valider'); ?>"
                                           style="font-size: 14px;width:100%;height:62px;"
                                           class="submitbutton btn btn-lg btn-success">
                                </p>
                                <button data-id="<?php echo $ph['id']; ?>"
                                        style="float:right; margin-right:3%;font-size: 14px;width:41%;height:62px;"
                                        type="button" class="btnBackToOrigImage btn btn-lg btn-default">Retour
                                    &agrave;<br>l'image d'origine
                                </button>
                                <button style="float:right; margin-right:3%;font-size: 14px;width:28%;height:62px;"
                                        type="button" class="btn btn-lg btn-default" data-dismiss="modal">Fermer<br>la
                                    fen&ecirc;tre
                                </button>
                                <p class="clearboth"></p>
                            </form>
                        </div>
                        <p class="clearboth"></p>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>

</div>
